"use strict";
exports.__esModule = true;
var MyStack_1 = require("./MyStack");
var MyQueue_1 = require("./MyQueue");
var numberStack = new MyStack_1["default"]([]);
numberStack.push(1);
numberStack.push(2);
var data_numberStack = numberStack.pop();
var stringStack = new MyStack_1["default"]([]);
stringStack.push("a");
stringStack.push("b");
var data_stringStack = stringStack.pop();
var numberQueue = new MyQueue_1["default"]([]);
numberQueue.offer(1);
numberQueue.offer(2);
var data_numberQueue = numberQueue.poll();
var stringQueue = new MyQueue_1["default"]([]);
stringQueue.offer("a");
stringQueue.offer("b");
var data_stringQueue = stringQueue.poll();
console.log([data_numberStack, data_stringStack, data_numberQueue, data_stringQueue]);
